### ISSUE TITLE
Error executing action `enable` on resource 'service[smbd]'

### ISSUE THREAD

**Issue by jakub82** [jtimberman/samba-cookbook#30]
Hi,

When I run recipe[samba::server] it fails with ```Error executing action `enable` on resource 'service[smbd]'``` on Ubuntu Server 15.04

output:
```
 * service[smbd] action enable
    
    ================================================================================
    Error executing action `enable` on resource 'service[smbd]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl enable smbd ----
    STDOUT: 
    STDERR: Synchronizing state for smbd.service with sysvinit using update-rc.d...
    Executing /usr/sbin/update-rc.d smbd defaults
    Executing /usr/sbin/update-rc.d smbd enable
    Failed to execute operation: No such file or directory
    ---- End output of /bin/systemctl enable smbd ----
    Ran /bin/systemctl enable smbd returned 1
    
    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/samba/recipes/server.rb
    
     60:   service s do
     61:     supports :restart => true, :reload => true
     62:     provider Chef::Provider::Service::Upstart if platform?('ubuntu') && node['platform_version'].to_f == 14.04
     63:     pattern 'smbd|nmbd' if node['platform'] =~ /^arch$/
     64:     action [:enable, :start]
     65:   end
     66: end
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/samba/recipes/server.rb:60:in `block in from_file'
    
    service("smbd") do
      action [:enable, :start]
      supports {:restart=>true, :reload=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "smbd"
      pattern "smbd"
      declared_type :service
      cookbook_name :samba
      recipe_name "server"
    end
    
  * service[smbd] action restart
    - restart service service[smbd]
  * service[nmbd] action restart
    - restart service service[nmbd]

Running handlers:
[2015-07-02T00:24:39+02:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-02T00:24:39+02:00] ERROR: Exception handlers complete
[2015-07-02T00:24:39+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 4 resources updated in 9.930227904 seconds
[2015-07-02T00:24:39+02:00] ERROR: service[smbd] (samba::server line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl enable smbd ----
STDOUT: 
STDERR: Synchronizing state for smbd.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d smbd defaults
Executing /usr/sbin/update-rc.d smbd enable
Failed to execute operation: No such file or directory
---- End output of /bin/systemctl enable smbd ----
Ran /bin/systemctl enable smbd returned 1
[2015-07-02T00:24:39+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

chef-stacktrace.out:
```
Generated at 2015-07-02 00:24:39 +0200
Mixlib::ShellOut::ShellCommandFailed: service[smbd] (samba::server line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl enable smbd ----
STDOUT: 
STDERR: Synchronizing state for smbd.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d smbd defaults
Executing /usr/sbin/update-rc.d smbd enable
Failed to execute operation: No such file or directory
---- End output of /bin/systemctl enable smbd ----
Ran /bin/systemctl enable smbd returned 1
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:278:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:265:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/service/systemd.rb:117:in `enable_service'
/opt/chef/embedded/apps/chef/lib/chef/provider/service.rb:66:in `block in action_enable'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:165:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/service.rb:65:in `action_enable'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:130:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:51:in `load'
/usr/bin/chef-solo:51:in `<main>'
```

**Comment by jakub82** [comment]
Looks like it is more related to systemd than cookbook itself: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1447807
